/*
 * This source file was generated by the Gradle 'init' task
 */
package algovisualizer;

import javax.swing.SwingUtilities;

import main.java.algovisualizer.AlgorithmVisualizer;

public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new AlgorithmVisualizer());
    }
}
